/*
Enter your query here. Mysql code
*/

SELECT CITY, LENGTH(CITY) AS CITY_LENGTH FROM STATION ORDER BY CITY_LENGTH, CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) AS CITY_LENGTH FROM STATION ORDER BY CITY_LENGTH DESC, CITY LIMIT 1;